server:
   port: 5555

spring:
    application:
        name: gateway
    cloud:
      gateway:
#        discovery:
#          locator:
#            enabled: false

        routes:
        - id: user-server
          uri: http://127.0.0.1:9988/
#          uri: lb://USER
          predicates:
          - Path=/**



eureka:
  client:
    registerWithEureka: true
     #是否从eureka获取服务信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: gateway-5555
    prefer-ip-address: true


#logging:
#  file: "/home/logs/ml-user-manager.log"