server:
   port: 9966

spring:
    application:
        name: portal-basic
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/asiainfo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 111111
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

eureka:
  client:
    registerWithEureka: true
     #是否从eureka获取服务信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: basic-9966
    prefer-ip-address: true

sjzt:
  app-health:
    # 数据中台--监控模块--服务健康监控--告警超时百分比（上报频率60秒，值为30，则 60+60*30% 秒内未上报不会为告警状态）
    alarmDelayPercent: 30
    # 数据中台--监控模块--服务健康监控--故障超时百分比
    faultDelayPercent: 50

#logging:
#  file: "D:\logs\user.log"