server:
   port: 8761

eureka:
   instance:
       hostname: 127.0.0.1
   client:
       registerWithEureka: false
       #是否从eureka获取服务信息
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/