server:
   port: 5555

spring:
    application:
        name: portal-gateway
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/asiainfo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 111111
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true #将请求路径上的服务名配置为小写

        routes:
        - id: user-server
#          uri: http://127.0.0.1:9988/
          uri: lb://user
          predicates:
          - Path=/api/**
          filters:
          - StripPrefix=1
          # 熔断降级配置
          - name: Hystrix
            args:
              name : default
              fallbackUri: 'forward:/defaultfallback'


# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true


eureka:
  client:
    registerWithEureka: true
     #是否从eureka获取服务信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: gateway-5555
    prefer-ip-address: true

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: always


#logging:
#  file: "D:\logs\gateway.log"